# ZMK config for Corne (nice!nano v2 / nRF52840)

CONFIG_ZMK_POINTING=y

# Mouse movement

# Bluetooth latency tuning
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# BLE TX power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Deep sleep after 15 min idle
CONFIG_ZMK_SLEEP=y

# OLED
CONFIG_ZMK_DISPLAY=y